<?php
/** @var Txwitch\Model\Game $game  */
/** @var $game Txwitch\Model\Game */
?>

<?php include '_layouts/header.phtml'; ?>

<a href="/games">Home</a> <a href="/app/logout" style="float: right">Logout</a>

<?php if (!empty ($header)) : ?>
    <h1><?php echo (htmlspecialchars($header)); ?></h1>
<?php else: ?>
    <h1>Twitch Top Games</a></h1>
<?php endif; ?>

<div class="game-block">
    <a href="/streams?lang=ru"><img src="https://static-cdn.jtvnw.net/ttv-static/404_boxart-240x320.jpg" border="0"/></a>
    <div class="game-title">
        <a href="/streams">Top Streams</a>
    </div>
</div>

<?php foreach ($games as $game) : ?>
    <div class="game-block">
        <div>
            <a href="/streams?game_id=<?php echo $game->getId(); ?>&lang=ru"><img src="<?php echo $game->getBoxArtUrl(); ?>" border="0"/></a>
        </div>
        <div class="game-title">
            <a href="/streams?game_id=<?php echo $game->getId(); ?>"><?php echo $game->getName(); ?></a>
        </div>
    </div>
<?php endforeach; ?>

<?php include '_layouts/footer.phtml'; ?>
